# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
resources:
  packages:
    - package: DownloadGithubtask
      type: Nuget
      version: 1.0.0
      connection: 'DownloadGithubtask'
      name: DownloadGithubtask/OctocatApp1
      trigger: true

pool:
  vmImage: ubuntu-latest

steps:
  - task: DownloadGitHubNugetPackage@1
    inputs:
      packageName: 'DownloadGithubtask/OctocatApp1'
      version: '1.0.0'


