# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
resources:
  packages:
    - package: DownloadGithubtask
      type: Nuget
      version: 3.0.0
      connection: 'nugetpublish'
      name: DownloadGithubtask/gitta
      trigger: true

pool:
  name: bskpool

steps:
  - task: DownloadGitHubNugetPackage@1
    inputs:
      packageName: 'DownloadGithubtask/gitta'
      externalEndpoints: 35f8f78a-58c7-4652-bedf-4545049082d1
      version: '3.0.0'


