trigger:

- main

pool: default

steps:

- task: UseDotNet@2.222.0

  displayName: Use .NET Core SDK 7.0.306

  inputs:

   packageType: 'sdk'

   version: 7.0.306

 
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'