# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
resources:
  packages:
    - package: DownloadGithubtask
      type: Nuget
      version: 4.0.0
      connection: 'nugetpublish'
      name: DownloadGitHubNugetPackageV1/OctocatApp1
      trigger: true

pool:
    name: server

steps:
  - task: DownloadGitHubNugetPackage@1
    inputs:
      packageName: 'DownloadGitHubNugetPackageV1/OctocatApp1'
      externalEndpoints: 35f8f78a-58c7-4652-bedf-4545049082d1
      version: '4.0.0'


